[language-server.gopls]
command = "/Users/icell/go/bin/gopls"

[language-server.clangd]
command = "/usr/bin/clangd"

[language-server.rust-analyzer]
command = "/Users/icell/.cargo/bin/rust-analyzer"

[language-server.typescript-language-server]
command = "/Users/icell/Library/pnpm/typescript-language-server"

[language-server.python-lsp-server]
command = "/opt/homebrew/bin/pylsp"

[[language]]
name = "go"
auto-format = true
language-servers = [ "gopls" ]

[[language]]
name = "c"
auto-format = true
indent = {tab-width=4, unit = " "}
language-servers = ["clangd"]

[[language]]
name = "cpp"
auto-format = true
indent = {tab-width=4, unit = " "}
language-servers = ["clangd"]

[[language]]
name = "rust"
auto-format = true
language-servers = ["rust-analyzer"]

[[language]]
name = "javascript"
auto-format = true
language-servers = ["typescript-language-server"]

[[language]]
name = "typescript"
auto-format = true
language-servers = ["typescript-language-server"]

[[language]]
name = "python"
auto-format = true
language-servers = ["python-lsp-server"]